### ISSUE TITLE
A few small things

### ISSUE THREAD

**Issue by b-t-k** [vr8hub/alexandre-dumas_the-vicomte-de-bragelonne_george-routledge-and-co#1]
Run *se find-mismatched-dashes* and *se find-mismatched-diacritics*—they both make changes.

I am assuming the unsemanticated `<i>'`s as thoughts is acceptable? ((oh, just saw the production notes....) But I am not sure the following is correct (but I could be wrong):  
(**Chapter 17**): `<i><i xml:lang="fr">Cuistre!</i></i>`   
(**Chapter 62**): `<i><i xml:lang="fr">Mordioux!</i></i>`   
(**Chapter 67**): `<i><i xml:lang="fr">Mordioux!</i></i> thought` 
(**Chapter 142**): `what he wished to know: <i><i xml:lang="fr">Mordioux!</i></i>.` 
(**Chapter 145**): `saying to himself, <i><i xml:lang="fr">Mordioux!</i>`   
Regardless of whether it's correct semantically, what it does do is render the thoughts in roman which  is a mistake in my books.

Why the choice to keep the Chapter numbers arabic instead of Roman? Is it because of the parts? I tried to find that in the SEMoS but couldn't… 7.1.5.1 sort of implies they should remain roman.

Regularize "Bell-Isle" vs "Belle-Isle"?

## Chapter 1
Comma outside quote: ‘Monsieur Raoul’, others may be put so significant

## Chapter 59
 Comma outside quote: you are ‘ugly’, not to leave people to believe

## Chapter 88
 Period outside quote: “You say ‘yes’ like a ‘no’. She has

## content.opf
- long desc: you don't need the comma after six: "typically divided into three, four, or occasionally as many as six, parts;"

## colophon
Missing `<abbr>`?: `<b epub:type="z3998:personal-name">George Routledge and Co.</b>.</p>`

**Comment by vr8hub** [comment]
Doh! I always manage to forget to run something. There are a few mismatched diacritics left, but I believe they are all valid.

Alex has a loose limit of 100 or so chapters for Roman (emphasis on _loose_: _Notre Dame de Paris_ had 120 and we kept it Roman); anything over uses decimal since the Roman numerals get a little messy after that. We have a few books in the corpus that use decimal (_Clarissa_, I believe, and a couple of others). I asked him before I started and he said decimal; the email should be in the group archive.

Re italics inside italics, that is standard behavior, both in general and in our corpus. If there is an emphasized word inside a non-English phrase, then that emphasized word would be roman. Conversely, if there was a non-English phrase inside an emphasized sentence, the phrase would be roman. Think of it as the italicized phrase being the opposite of its surrounding text. If the surrounding text is roman, it's italicized. If the surrounding text is italics, it's roman.

Yes, Bell-Isle should definitely be standardized, good catch!

The punctuation and content/colophon items are fixed.

**Comment by b-t-k** [comment]
I guess you are technically correct about the italic/italic issue—I had really thought of it as emphasis since its not an `<em>` but especially the one in Chap 142 really makes it less clear given the lack of quotes.

**Comment by vr8hub** [comment]
Right, in those situations where it's the first word that's double-italics (and thus roman), then it's not always clear. In Gibbon, I have a number of instances where the first word of a non-English quote is emphasized, e.g. `<i xml:lang="la"><em>Argentifodinae</em> in Hercyniis montibus, imperante Othone magno</i>`. That comes out as
Argentifodinae _Hercyniis montibus, imperante Othone magno_
which makes the first word blend in with the text leading up to the quote.
If it was a different word, e.g.
_Argentifodinae Hercyniis montibus,_ imperante _Othone magno_
then it's more obvious what's going on.

The instances in _Braggelone_ aren't emphasis, but they're still italics within italics, and the standard CSS (it's in core) for that is to make it roman. (Actually, technically it's "normal", but for us normal text is almost always roman.)
